import type { Template } from '../types';

export const BUILT_IN_TEMPLATE_IDS = ['employee', 'student', 'visitor', 'event-pass', 'minimal'] as const;
export type BuiltInTemplateId = (typeof BUILT_IN_TEMPLATE_IDS)[number];

export const builtInTemplates: Record<BuiltInTemplateId, Template> = {
  employee: {
    id: 'employee',
    name: 'Employee',
    elements: [
      {
        id: 'emp-name',
        type: 'text',
        x: 5,
        y: 10,
        width: 60,
        height: 12,
        placeholder: 'Full Name',
        binding: 'name',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1a1a1a',
      },
      {
        id: 'emp-id',
        type: 'text',
        x: 5,
        y: 28,
        width: 40,
        height: 10,
        placeholder: 'ID',
        binding: 'id',
        fontSize: 12,
        color: '#333',
      },
      {
        id: 'emp-dept',
        type: 'text',
        x: 5,
        y: 42,
        width: 55,
        height: 10,
        placeholder: 'Department',
        binding: 'department',
        fontSize: 11,
        color: '#555',
      },
      {
        id: 'emp-photo',
        type: 'image',
        x: 65,
        y: 8,
        width: 28,
        height: 45,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: { type: 'solid', value: '#f5f5f5' },
    watermark: null,
  },
  student: {
    id: 'student',
    name: 'Student',
    elements: [
      {
        id: 'stu-name',
        type: 'text',
        x: 5,
        y: 8,
        width: 55,
        height: 14,
        placeholder: 'Student Name',
        binding: 'name',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#1a1a1a',
      },
      {
        id: 'stu-id',
        type: 'text',
        x: 5,
        y: 26,
        width: 45,
        height: 10,
        placeholder: 'Student ID',
        binding: 'id',
        fontSize: 11,
        color: '#333',
      },
      {
        id: 'stu-course',
        type: 'text',
        x: 5,
        y: 40,
        width: 55,
        height: 10,
        placeholder: 'Course',
        binding: 'course',
        fontSize: 10,
        color: '#555',
      },
      {
        id: 'stu-photo',
        type: 'image',
        x: 65,
        y: 5,
        width: 28,
        height: 50,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: { type: 'gradient', value: '#E3F2FD', gradientDirection: 'to bottom', gradientColor2: '#BBDEFB' },
    watermark: null,
  },
  visitor: {
    id: 'visitor',
    name: 'Visitor',
    elements: [
      {
        id: 'vis-name',
        type: 'text',
        x: 5,
        y: 12,
        width: 60,
        height: 12,
        placeholder: 'Visitor Name',
        binding: 'name',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#1a1a1a',
      },
      {
        id: 'vis-company',
        type: 'text',
        x: 5,
        y: 28,
        width: 60,
        height: 10,
        placeholder: 'Company',
        binding: 'company',
        fontSize: 11,
        color: '#333',
      },
      {
        id: 'vis-date',
        type: 'text',
        x: 5,
        y: 42,
        width: 55,
        height: 10,
        placeholder: 'Date',
        binding: 'date',
        fontSize: 10,
        color: '#555',
      },
      {
        id: 'vis-photo',
        type: 'image',
        x: 68,
        y: 8,
        width: 26,
        height: 45,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: { type: 'solid', value: '#FFF8E1' },
    watermark: null,
  },
  'event-pass': {
    id: 'event-pass',
    name: 'Event Pass',
    elements: [
      {
        id: 'ev-name',
        type: 'text',
        x: 10,
        y: 8,
        width: 80,
        height: 14,
        placeholder: 'Name',
        binding: 'name',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1a1a1a',
      },
      {
        id: 'ev-event',
        type: 'text',
        x: 10,
        y: 28,
        width: 80,
        height: 10,
        placeholder: 'Event',
        binding: 'event',
        fontSize: 11,
        color: '#333',
      },
      {
        id: 'ev-photo',
        type: 'image',
        x: 35,
        y: 42,
        width: 30,
        height: 45,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: { type: 'gradient', value: '#FCE4EC', gradientDirection: 'to right', gradientColor2: '#F8BBD9' },
    watermark: null,
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    elements: [
      {
        id: 'min-name',
        type: 'text',
        x: 10,
        y: 15,
        width: 55,
        height: 14,
        placeholder: 'Name',
        binding: 'name',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1a1a1a',
      },
      {
        id: 'min-id',
        type: 'text',
        x: 10,
        y: 35,
        width: 55,
        height: 10,
        placeholder: 'ID',
        binding: 'id',
        fontSize: 11,
        color: '#333',
      },
      {
        id: 'min-photo',
        type: 'image',
        x: 68,
        y: 10,
        width: 25,
        height: 55,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: { type: 'solid', value: '#ffffff' },
    watermark: null,
  },
};

export function getBuiltInTemplate(id: string): Template | null {
  if (BUILT_IN_TEMPLATE_IDS.includes(id as BuiltInTemplateId)) {
    const t = builtInTemplates[id as BuiltInTemplateId];
    return { ...t, elements: t.elements.map((e) => ({ ...e })) };
  }
  return null;
}
