import type { Template } from '../types';

export const BUILT_IN_TEMPLATES: Template[] = [
  {
    id: 'employee',
    name: 'Employee',
    elements: [
      {
        id: 'emp-name',
        type: 'text',
        x: 55,
        y: 5,
        width: 40,
        height: 15,
        placeholder: 'Name',
        binding: 'name',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1a1a1a',
      },
      {
        id: 'emp-id',
        type: 'text',
        x: 55,
        y: 22,
        width: 40,
        height: 12,
        placeholder: 'ID',
        binding: 'id',
        fontSize: 11,
        fontWeight: 'normal',
        color: '#333',
      },
      {
        id: 'emp-dept',
        type: 'text',
        x: 55,
        y: 36,
        width: 40,
        height: 12,
        placeholder: 'Department',
        binding: 'department',
        fontSize: 10,
        fontWeight: 'normal',
        color: '#555',
      },
      {
        id: 'emp-photo',
        type: 'image',
        x: 5,
        y: 5,
        width: 45,
        height: 70,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: {
      type: 'gradient',
      value: '#4A90D9',
      gradientColor2: '#357ABD',
      gradientDirection: 'to bottom',
    },
    watermark: null,
  },
  {
    id: 'student',
    name: 'Student',
    elements: [
      {
        id: 'stu-name',
        type: 'text',
        x: 5,
        y: 5,
        width: 90,
        height: 18,
        placeholder: 'Student Name',
        binding: 'name',
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1a1a2e',
      },
      {
        id: 'stu-id',
        type: 'text',
        x: 5,
        y: 28,
        width: 90,
        height: 12,
        placeholder: 'Student ID',
        binding: 'id',
        fontSize: 11,
        fontWeight: 'normal',
        color: '#333',
      },
      {
        id: 'stu-course',
        type: 'text',
        x: 5,
        y: 45,
        width: 90,
        height: 12,
        placeholder: 'Course',
        binding: 'course',
        fontSize: 10,
        fontWeight: 'normal',
        color: '#555',
      },
      {
        id: 'stu-photo',
        type: 'image',
        x: 5,
        y: 60,
        width: 40,
        height: 35,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: {
      type: 'solid',
      value: '#E8F5E9',
    },
    watermark: {
      type: 'text',
      value: 'STUDENT',
      opacity: 0.15,
      position: 'center',
      fontSize: 24,
      rotation: -15,
    },
  },
  {
    id: 'visitor',
    name: 'Visitor',
    elements: [
      {
        id: 'vis-photo',
        type: 'image',
        x: 5,
        y: 5,
        width: 35,
        height: 75,
        placeholder: 'Photo',
        binding: 'photo',
      },
      {
        id: 'vis-name',
        type: 'text',
        x: 45,
        y: 10,
        width: 50,
        height: 15,
        placeholder: 'Visitor Name',
        binding: 'name',
        fontSize: 13,
        fontWeight: 'bold',
        color: '#000',
      },
      {
        id: 'vis-company',
        type: 'text',
        x: 45,
        y: 30,
        width: 50,
        height: 12,
        placeholder: 'Company',
        binding: 'company',
        fontSize: 10,
        fontWeight: 'normal',
        color: '#444',
      },
      {
        id: 'vis-date',
        type: 'text',
        x: 45,
        y: 48,
        width: 50,
        height: 10,
        placeholder: 'Visit Date',
        binding: 'date',
        fontSize: 9,
        fontWeight: 'normal',
        color: '#666',
      },
    ],
    background: {
      type: 'solid',
      value: '#FFF8E1',
    },
    watermark: {
      type: 'text',
      value: 'VISITOR',
      opacity: 0.12,
      position: 'top-right',
      fontSize: 18,
      rotation: 25,
    },
  },
  {
    id: 'event',
    name: 'Event Pass',
    elements: [
      {
        id: 'evt-name',
        type: 'text',
        x: 10,
        y: 10,
        width: 80,
        height: 20,
        placeholder: 'Attendee Name',
        binding: 'name',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
      },
      {
        id: 'evt-ticket',
        type: 'text',
        x: 10,
        y: 35,
        width: 80,
        height: 12,
        placeholder: 'Ticket #',
        binding: 'id',
        fontSize: 11,
        fontWeight: 'normal',
        color: '#e0e0e0',
      },
      {
        id: 'evt-photo',
        type: 'image',
        x: 10,
        y: 55,
        width: 35,
        height: 40,
        placeholder: 'Photo',
        binding: 'photo',
      },
    ],
    background: {
      type: 'gradient',
      value: '#6B2D5C',
      gradientColor2: '#9B3B7A',
      gradientDirection: 'to right',
    },
    watermark: null,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    elements: [
      {
        id: 'min-photo',
        type: 'image',
        x: 5,
        y: 5,
        width: 40,
        height: 85,
        placeholder: 'Photo',
        binding: 'photo',
      },
      {
        id: 'min-name',
        type: 'text',
        x: 50,
        y: 30,
        width: 45,
        height: 20,
        placeholder: 'Name',
        binding: 'name',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000',
      },
      {
        id: 'min-id',
        type: 'text',
        x: 50,
        y: 55,
        width: 45,
        height: 12,
        placeholder: 'ID',
        binding: 'id',
        fontSize: 10,
        fontWeight: 'normal',
        color: '#333',
      },
    ],
    background: {
      type: 'solid',
      value: '#ffffff',
    },
    watermark: null,
  },
];
